---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  root_password: cm9vdA==
  #root
  username: cGV0Y2xpbmlj
  password: cGV0Y2xpbmlj
  database: cGV0Y2xpbmlj
  #cGV0Y2xpbmlj is petclinic