---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  selector:
    app: spc
    tier: app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080    
  type: LoadBalancer